-- NAMES: DREW GARRISON AND NICK FUNKHOUSER
-- DATE: 3/31/2022

USE TaylorPizzeria;


DROP TABLE IF EXISTS pizza_order;

DROP TABLE IF EXISTS delivery;

DROP TABLE IF EXISTS dinein;

DROP TABLE IF EXISTS pickup;

DROP TABLE IF EXISTS pizza;

DROP TABLE IF EXISTS customer;

DROP TABLE IF EXISTS customer_order;

DROP TABLE IF EXISTS discount;

DROP TABLE IF EXISTS baseprice;

DROP TABLE IF EXISTS TOPPING;



